apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: interactive-website
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: interactive-website
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: interactive-website-cert
    - hosts:
        - medienmäntor.de
      secretName: interactive-website-cert-2
